# Generated by Django 2.2 on 2020-04-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roles', models.CharField(choices=[('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT'), ('HOSPITAL', 'HOSPITAL')], max_length=100)),
            ],
        ),
    ]
