# Generated by Django 2.2 on 2020-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='dateofreg',
            field=models.DateField(null=True),
        ),
    ]
