# Generated by Django 2.2 on 2020-04-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0002_treatmentcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('REQUESTED', 'REQUESTED'), ('NA', 'NA')], max_length=100)),
                ('appointment', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.PatientProfile')),
            ],
        ),
    ]
