# Generated by Django 2.2 on 2020-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200513_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttreatment',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patienttreatment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
