# Generated by Django 2.2 on 2020-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200514_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('REQUESTED', 'REQUESTED'), ('NA', 'NA'), ('DONE', 'DONE')], max_length=100),
        ),
    ]
